import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { siteConfig } from "@/data/siteConfig";

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default:
      "Lunamar Digital | No-Upfront Websites for Serious Small Businesses",
    template: "%s | Lunamar Digital",
  },
  description: siteConfig.description,
  keywords: [
    "web design",
    "website development",
    "SEO",
    "local SEO",
    "social media management",
    "digital marketing",
    "monthly website plans",
    "Lunamar Digital",
  ],
  applicationName: siteConfig.name,
  authors: [{ name: siteConfig.name }],
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    siteName: siteConfig.name,
    title:
      "Lunamar Digital | No-Upfront Websites for Serious Small Businesses",
    description: siteConfig.description,
    url: siteConfig.url,
    // Social images are generated by app/opengraph-image.tsx + twitter-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title:
      "Lunamar Digital | No-Upfront Websites for Serious Small Businesses",
    description: siteConfig.description,
  },
  robots: { index: true, follow: true },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en-GB"
      data-scroll-behavior="smooth"
    >
      <body>
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-full focus:bg-white focus:px-5 focus:py-2.5 focus:text-sm focus:font-medium focus:text-black"
        >
          Skip to content
        </a>
        <Header />
        <main id="main">{children}</main>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
